export const IPC = {
    SEARCH_QUERY: 'search:query',
    SEARCH_BATCH: 'search:batch',
    SEARCH_CANCEL: 'search:cancel',
    PLUGIN_EXEC: 'plugin:exec',
    PLUGIN_RUNTIME_STATE: 'plugin:runtime-state',
    HOST_SWITCH: 'host:switch',
    HOST_VIEW_ATTACHED: 'host:view-attached',
    HOST_VIEW_DETACHED: 'host:view-detached',
    WINDOW_RESIZE: 'window:resize',
    WINDOW_HIDE: 'window:hide',
    WINDOW_SHOW: 'window:show',
    THEME_CHANGED: 'theme:changed',
    THEME_GET: 'theme:get',
    PLUGIN_SEARCH: 'plugin:search',
    PLUGIN_SEARCH_RESULT: 'plugin:search-result',
    PLUGIN_ENTER: 'plugin:enter',
    PLUGIN_CLOSE: 'plugin:close',
} as const;
